### PR TITLE
Update fixes 2

### PR DESCRIPTION
**Pull request by TheVeryDarkness**
A problem that I meet is how generated enum `Rule` from imported modules can be used in modules that they are imported into. And error tracker may also need this to work.
Say, there is two modules `a` and `b`, and `a` is importing `b`. Maybe I need to add a variant `b(b::Rule)` in `enum Rule` generated for `a`, like

```
/// For module `a`.
enum Rule {
    b(rules::b::Rule),
    ...
}
pub mod rules {
    pub mod b {
        /// For module `b`.
        pub enum Rule {
            ...
        }
    }
    ...
}
```

However, definitions of some traits need also to be changed. I may need some time to evaluate this. @tomtau What's your point?

_See [da60a73c77bef02caaf4bd33b3a7df85e7571141](https://github.com/TheVeryDarkness/pest3/commit/da60a73c77bef02caaf4bd33b3a7df85e7571141) for details_

### CODE REVIEW

**Comment by tomtau** [comment]
> However, definitions of some traits need also to be changed. I may need some time to evaluate this. @tomtau What's your point?

@TheVeryDarkness could you describe more what the issue is? Is it that the imported modules would otherwise be marked / warned as unused ?

**Comment by tomtau** [comment]
Or that for access by the caller / user?

**Comment by TheVeryDarkness** [comment]
It's mainly about generics arguments and types.
For example, there is an generics argument `R` in both `Rule<'i, R>` and `TypedNode<'i, R>`, and `R` for different modules aren't the same, unless we flatten them in a single enum (but this may lead to a mess in names).
And current implementations only work on the same `Rule`. For example, `Sequence2<a, b>` (unrelated arguments omitted) won't implement `TypeNode<'i, Rule>` if `a` and `b` are from module `b` and implement `TypedNode<'i, b::Rule>` only (worse situation is `a` and `b` are from different modules).

**Comment by tomtau** [comment]
@TheVeryDarkness 
> unless we flatten them in a single enum (but this may lead to a mess in names)

Flattening seems like a simpler solution, so I guess we can go with that for now.
(But later, it sounds like there should be a better solution to that.)

**Comment by TheVeryDarkness** [comment]
@tomtau I figured out a method to handle the problem mentioned above without flattening the rules! We can implement the `TypedNode` or similar traits for every related rule type.

```pest
// a.pest
a = "a"
```

```pest
// b.pest
use a::a
b = a - "b"
```

```rust
/// For a.pest
pub enum Rule {
    ...
}
mod rules {
    pub mod b {
        /// For b.pest
        pub enum Rule {
            ...
        }
    }
}
```

`TypedNode<'i, Rule>` should be implemented for types from `a.pest` and `b.pest`, and `TypedNode<'i, rules::b::Rule>` should be implemented for types from `b.pest`.

And by this method, we can implement the whole parser without flattening the rules.

**Comment by TheVeryDarkness** [comment]
Maybe you can add more tests about imports? And I have something to explain here about my implementation. If you disagree with my implementation, just tell me about your opinions.

- I added a component in import statements to support specifying the path of imported module. It uses `in`, and it's like `use some::module in "path/to/the/module.pest"`.
   See [grammar.pest](https://github.com/TheVeryDarkness/pest3/blob/a58f09634e541d1f93c7d7daf8d2d8e80a292ded/meta/src/grammar.pest#L14) for details.
- Following your suggestion, the module path `super::mod1::mod2::mod3` will be converted to `../mod1/mod2/mod3`, which you can see in [parser::mod_path_to_fs_path](https://github.com/TheVeryDarkness/pest3/blob/a58f09634e541d1f93c7d7daf8d2d8e80a292ded/meta/src/parser.rs#L260-L270) and [parser::_parse](https://github.com/TheVeryDarkness/pest3/blob/a58f09634e541d1f93c7d7daf8d2d8e80a292ded/meta/src/parser.rs#L292-L336).
  There may be some problems about the priority of specified path and generated in my current implementation, and I'll fix them later.
- As we can't get source file path in proc macros on stable channel for now, we can't get to know which file the inline grammar is in. I give it a virtual path, `$MANIFEST_PATH/_.rs`, and imported file will be resolved from this path.
   For example, for a crate like below:

   ```txt
   - src/
      - lib.rs
      - bar/
         - mod.rs
         - bar1.rs
         - bar2.rs
   - tests/
      - a.pest
      - b.pest
      - foo.rs
   - Cargo.toml
   ```

   No matter in which rust file, as long as users write the import statement in the attribute `grammar_inline`, users should write `use tests::a` or `use a in "tests/a.pest"` to import the module defined in `tests/a.pest`.
- But import statements in `*.pest` will be resolved from the pest grammar file itself. So in `tests/a.pest`, it's enough for users to write `use b` or `use b in "b"` to import `tests/b.pest`.

**Comment by tomtau** [comment]
> Maybe you can add more tests about imports? And I have something to explain here about my implementation. If you disagree with my implementation, just tell me about your opinions.

I'll try to look into it in the upcoming days. From what you described, it sounds all right for this initial prototype
(the module system will likely need some re-work and more well-defined behaviours in the future, but we can go with what you sketched out for now).
Do you plan some more work on the typed API (the more favourable style, not the one mimicking pairs) or it's ok to add more tests for it?

**Comment by TheVeryDarkness** [comment]
> > Maybe you can add more tests about imports? And I have something to explain here about my implementation. If you disagree with my implementation, just tell me about your opinions.
> 
> I'll try to look into it in the upcoming days. From what you described, it sounds all right for this initial prototype
> (the module system will likely need some re-work and more well-defined behaviours in the future, but we can go with what you sketched out for now).
> Do you plan some more work on the typed API (the more favourable style, not the one mimicking pairs) or it's ok to add more tests for it?

Yes, I'll add accesser API later, during which I may add some tests.

And looking forward to your feedback.

**Comment by tomtau** [comment]
will continue on this one: https://github.com/pest-parser/pest3/pull/4

**Pull request closed without merging**
